# Generated for Django 5
import django.db.models.deletion
import inventory.models
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100, verbose_name="Ad")), ("is_active", models.BooleanField(default=True, verbose_name="Aktif")), ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Sıra")), ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="inventory.category", verbose_name="Üst kategori"))], options={"ordering": ["sort_order", "name"]}),
        migrations.CreateModel(name="Person", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=100, unique=True, verbose_name="Ad")), ("is_active", models.BooleanField(default=True, verbose_name="Aktif"))], options={"ordering": ["name"], "verbose_name": "Kişi", "verbose_name_plural": "Kişiler"}),
        migrations.CreateModel(name="StorageUnit", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=150, unique=True, verbose_name="Ad")), ("unit_type", models.CharField(choices=[("VACUUM_BAG", "Vakum poşeti"), ("SUITCASE", "Valiz"), ("SHELF", "Raf"), ("DRAWER", "Çekmece"), ("HANGING", "Askılık bölümü"), ("OTHER", "Diğer")], max_length=20, verbose_name="Tür")), ("location_text", models.CharField(max_length=255, verbose_name="Fiziksel konum")), ("description", models.TextField(blank=True, verbose_name="Açıklama")), ("is_active", models.BooleanField(default=True, verbose_name="Aktif"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Tag", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True, verbose_name="Ad")), ("slug", models.SlugField(blank=True, unique=True)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Item", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=180, verbose_name="Ürün adı")), ("brand", models.CharField(blank=True, max_length=100, verbose_name="Marka")), ("model", models.CharField(blank=True, max_length=100, verbose_name="Model")), ("primary_color", models.CharField(max_length=60, verbose_name="Ana renk")), ("secondary_color", models.CharField(blank=True, max_length=60, verbose_name="İkincil renk")), ("size", models.CharField(blank=True, max_length=30, verbose_name="Beden")), ("waist_size", models.CharField(blank=True, max_length=30, verbose_name="Bel ölçüsü")), ("inseam_size", models.CharField(blank=True, max_length=30, verbose_name="Paça uzunluğu")), ("shoe_size", models.CharField(blank=True, max_length=20, verbose_name="Ayakkabı numarası")), ("material", models.CharField(blank=True, max_length=80, verbose_name="Kumaş")), ("pattern", models.CharField(blank=True, max_length=80, verbose_name="Desen")), ("fit", models.CharField(blank=True, max_length=80, verbose_name="Fit")), ("season", models.CharField(blank=True, max_length=80, verbose_name="Mevsim")), ("status", models.CharField(choices=[("ACTIVE", "Envanterde"), ("TO_SELL", "Satılacak"), ("TO_DONATE", "Bağışlanacak"), ("SOLD", "Satıldı"), ("DONATED", "Bağışlandı"), ("ARCHIVED", "Arşivlendi"), ("LOST", "Kayıp")], default="ACTIVE", max_length=20, verbose_name="Durum")), ("notes", models.TextField(blank=True, verbose_name="Notlar")), ("archived_at", models.DateTimeField(blank=True, null=True)), ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="inventory.category", verbose_name="Kategori")), ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="inventory.person", verbose_name="Kişi")), ("storage_unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="inventory.storageunit", verbose_name="Saklama birimi")), ("tags", models.ManyToManyField(blank=True, related_name="items", to="inventory.tag", verbose_name="Etiketler"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="Photo", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("image", models.ImageField(upload_to=inventory.models.photo_path, verbose_name="Fotoğraf")), ("thumbnail", models.ImageField(blank=True, upload_to=inventory.models.thumbnail_path, verbose_name="Thumbnail")), ("is_cover", models.BooleanField(default=False, verbose_name="Ana fotoğraf")), ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Sıra")), ("created_at", models.DateTimeField(auto_now_add=True)), ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="inventory.item", verbose_name="Ürün"))], options={"ordering": ["sort_order", "created_at"]}),
        migrations.AddConstraint(model_name="category", constraint=models.UniqueConstraint(fields=("parent", "name"), name="unique_category_parent_name")),
        migrations.AddConstraint(model_name="photo", constraint=models.UniqueConstraint(condition=models.Q(("is_cover", True)), fields=("item",), name="one_cover_per_item")),
        migrations.AddIndex(model_name="storageunit", index=models.Index(fields=["unit_type", "is_active"], name="inventory_s_unit_ty_5da087_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["status", "archived_at"], name="inventory_i_status_919cd0_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["person", "category"], name="inventory_i_person__ab3c85_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["primary_color"], name="inventory_i_primary_17917f_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["brand"], name="inventory_i_brand_18c50c_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["storage_unit"], name="inventory_i_storage_1740e7_idx")),
    ]
